### ISSUE TITLE
Missing licence file

### ISSUE THREAD

**Issue by zymotik** [dawoe/OEmbed-Picker-Property-Editor#1]
Hi, please can you add a licence for this code so that we understand how we can use it. Thanks. Ian

**Comment by dawoe** [comment]
Hi @zymotik 

I'm working on a new version for Umbraco 8. I will include the license file in that release. It's MIT licensed

**Comment by zymotik** [comment]
Thank you Dave

**Comment by dawoe** [comment]
Hi 

The license is now added to the project
