### ISSUE TITLE
Embed doesn't work when using vimeoUrl.

### ISSUE THREAD

**Issue by jkulker** [dawoe/OEmbed-Picker-Property-Editor#13]
Hi,

Strange error. When trying to embed a vimeo url it is not possible to retrieve the video. This problem occurs on every envi in the cloud. 

Localhost i don't have the problem.

Running latest Umbraco 8 in the cloud

error: Could not embed media - please ensure the URL is valid
url used: https://vimeo.com/451441279

**Comment by dawoe** [comment]
Hi @jkulker 

Could you try if you can embed it using the embed option in the rich text editor ?

Because I'm using the built in embed functionality for retreiving the embed code.

Dave

**Comment by jkulker** [comment]
Have the same problem on the default on the richt text

**Comment by dawoe** [comment]
And only on cloud. Not locally ?

**Comment by jkulker** [comment]
that is correct

**Comment by dawoe** [comment]
Then I would recommend to open a issue here : https://github.com/umbraco/Umbraco.Cloud.Issues/issues

Dave

**Comment by jkulker** [comment]
So reply from Umbraco:

The reason you're seeing this is because Vimeo has implemented a ban on the Umbraco Cloud IP address.
I have previously investigated this with help from Vimeo support I've narrowed this issue down to the following:

Random site makes way too many requests to the Vimeo API

Vimeo implements a 24 hour ban on the IP the site currently has

The ban is into effect for all Cloud sites currently on that IP

you can close this issue
