### ISSUE TITLE
Add edit button

### ISSUE THREAD

**Issue by bjarnef** [dawoe/OEmbed-Picker-Property-Editor#14]
It would be great to add a edit button to make it possible to adjust the embed url, but also the default width, height, etc.

I previous added this to the default Embed grid editor in this PR: https://github.com/umbraco/Umbraco-CMS/pull/4899 and later some changes to make it work after again after some changes: https://github.com/umbraco/Umbraco-CMS/pull/8576

Although the embed can just be removed and re-added, it might be an issue to content editors if they don't know the original url and it might not be easy to a non-technical person to find the url.

**Comment by dawoe** [comment]
Good idea @bjarnef

**Comment by dawoe** [comment]
Just released 4.3.0 that contains your pr.
