### ISSUE TITLE
Some embed previews overflow preview item

### ISSUE THREAD

**Issue by bjarnef** [dawoe/OEmbed-Picker-Property-Editor#17]
When embedding e.g. a tweet, this overflow the embed preview, e.g. this tweet https://twitter.com/umbraco/status/1402194892764372996

![image](https://user-images.githubusercontent.com/2919859/121324983-86e95e00-c911-11eb-82ff-5de326feec24.png)

We could add `overflow: hidden` to `preview-item` class, but `display: inline-block` may be nicer (at least in single mode).

![image](https://user-images.githubusercontent.com/2919859/121325345-d039ad80-c911-11eb-9a90-427d0c07a793.png)

**Comment by dawoe** [comment]
Hi @bjarnef 

Thanks for raising the issue. Will have a look after CG. To be honest I did not know that you could embed tweets. Our customer main usage is Youtube and Vimeo.

Dave
