### ISSUE TITLE
Use umb-icon component

### ISSUE THREAD

**Issue by bjarnef** [dawoe/OEmbed-Picker-Property-Editor#19]
A few placed the editor use the following to show icons.

```
<i class="icon icon-navigation handle" aria-hidden="true"></i>
```

Maybe in a new multi-target version for Umbraco v8.17 and v9 we could use this instead:

```
<umb-icon icon="icon-navigation" class="icon handle"></umb-icon>
```

**Comment by dawoe** [comment]
This is part of the V10 release
