### ISSUE TITLE
Umbraco 8 support

### ISSUE THREAD

**Issue by vonbarnekowa** [dawoe/OEmbed-Picker-Property-Editor#2]
Hey,

Great plugin! Would it be possible to update (if needed?) the code and the nuget so we can install it on Umbraco 8.

**Comment by dawoe** [comment]
Hi @vonbarnekowa 

I'm currently working on a V8 version. I hope to release it by the beginning of next week

**Comment by dawoe** [comment]
Hi @vonbarnekowa 

I just released v4 of this package that is compatible with Umbraco V8

So I will close this issue
