### ISSUE TITLE
No Title Attribute on iFrame

### ISSUE THREAD

**Issue by JamieHughes93** [dawoe/OEmbed-Picker-Property-Editor#20]
This editor doesn't allow for adding title attributes to the iframe accessibility purposes, it should at least display a generic "Video player" title. :)

**Comment by dawoe** [comment]
Hi @JamieHughes93 

There is now an extension method added in 5.1.0 that allows you to get the src attribute of the iframe in the generated embed code. This will give you the option to write your own embed code.

Dave
