### ISSUE TITLE
Umbraco v10 support

### ISSUE THREAD

**Issue by bjarnef** [dawoe/OEmbed-Picker-Property-Editor#24]
We have a project on Umbraco v9 using the OEmbed Picker, which we are intending to upgrade to Umbraco v10.
Does the package work on v10 / .NET6 or does it need a new build for this?

On Umbraco v9 I noticed this issue when switching property editor. May be worth including as well.
https://github.com/dawoe/OEmbed-Picker-Property-Editor/pull/23

However I think it would be nice to integrate this in core to benefits from this as it mainly wraps existing functionality:
https://github.com/umbraco/Umbraco-CMS/pull/12609

**Comment by dawoe** [comment]
The V10 version has just been released
