### ISSUE TITLE
3rd Party Support

### ISSUE THREAD

**Issue by jaymarvels** [dawoe/OEmbed-Picker-Property-Editor#28]
Version : Umb 10.4.0
Package version: 10

Have tried to use a Facebook post url and I get the error back "not supported"

Have tried to use a LinkedIn post url and I get the error back "not supported"

Have tried to use a Instragm post url and I get the error back "not supported"

I have tested using the posts urls. They also provide oembed html which is also "not supported"

Is there something missing?

**Comment by dawoe** [comment]
Hi @jaymarvels 

Apologies for the late response. I must have missed the notification of this issue being created.

My property editor uses the built-in functionality of Umbraco Core. If reports back as not supported that probably means it is not supported in Umbraco.

The documentation lists all supported providers : https://docs.umbraco.com/umbraco-cms/extending/embedded-media-providers#embed-provider-configuration
