### ISSUE TITLE
Property value converter broken in 8.1

### ISSUE THREAD

**Issue by dawoe** [dawoe/OEmbed-Picker-Property-Editor#3]
See https://our.umbraco.com/packages/backoffice-extensions/oembed-picker-property-editor/questions-bugs-feedback-etc/98236-property-value-converter-always-returning-null-on-v81

**Comment by filefontaine** [comment]
Hello
I'm testing your prerelease and it's work for me.
a fast patching compared to other,
 thanks a lot.

**Comment by dawoe** [comment]
Hi @filefontaine 

Thanks for testing. I'm hoping to get a another positive test from the original reporter. Expect a official release this week.

Dave

**Comment by dawoe** [comment]
I got confirmation from the original reporter that it works on the beta. So I released 4.1.0 that is compatible with Umbraco 8.1.0
