### ISSUE TITLE
Set version in PackageManifestFilter

### ISSUE THREAD

**Issue by bjarnef** [dawoe/OEmbed-Picker-Property-Editor#31]
Is it possible to set the version in `PackageManifestFilter` class?

![image](https://github.com/dawoe/OEmbed-Picker-Property-Editor/assets/2919859/035c84ee-2921-4211-8d1b-7a4ce405ce98)

So it is shown here.

![image](https://github.com/dawoe/OEmbed-Picker-Property-Editor/assets/2919859/5bcc4cc0-5e69-441c-8262-3639157ff8f7)

E.g. [Bergmania.OpenStreetMap](https://github.com/bergmania/Bergmania.OpenStreetMap) have a version set here:
https://github.com/bergmania/Bergmania.OpenStreetMap/blob/5b84fddc9d8bc7ad729dcf80a107c7b99da21bbb/Bergmania.OpenStreetMap.StaticAssets/wwwroot/App_Plugins/Bergmania.OpenStreetMap/package.manifest#L3

**Comment by dawoe** [comment]
Hi @bjarnef 

This will be part of the 12.1.0 release and future versions.

Dave
