### ISSUE TITLE
Question: Do we need a custom EmbedPropertyIndexValueFactory?

### ISSUE THREAD

**Issue by mistyn8** [dawoe/OEmbed-Picker-Property-Editor#32]
![image](https://github.com/dawoe/OEmbed-Picker-Property-Editor/assets/12418214/90f4c395-088d-484f-8601-abd8b97d0f1e)

I was expecting this to see the valueType as JSON and index as keyvalue pairs, but doesn't seem to be the case?
https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/PropertyEditors/JsonPropertyIndexValueFactoryBase.cs

Or perhaps this is complicated by it being in the blockGrid, rather than a top level doctype property?

`public override IPropertyIndexValueFactory PropertyIndexValueFactory => _tagPropertyIndexValueFactory;`
https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Infrastructure/PropertyEditors/TagsPropertyEditor.cs#L89 is perhaps how tags does it?

**Comment by mistyn8** [comment]
Quick example with tags..
![image](https://github.com/dawoe/OEmbed-Picker-Property-Editor/assets/12418214/76442687-22e9-4bc2-8fe7-cb97d26a142f)
Seems to index key values, and also drops from the main gridContent.

**Comment by dawoe** [comment]
Hi @mistyn8 

First and apology for the late reply. Are you sure this index data is coming from my property editor. I see a properties like constrain and info in there. That is something I don't see in the data indexed by my property editor.

```
[{"url":"https://www.youtube.com/watch?v=Q5k7a9YEoUI","width":360,"height":240,"preview":"<iframe width=\"360\" height=\"203\" src=\"https://www.youtube.com/embed/Q5k7a9YEoUI?feature=oembed\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen title=\"(OLD VERSION) Intro to Agile Scrum in Under 10 Minutes\"></iframe>"}]
```
What benefits would having them indexed the data as key value pairs bring to you ?

**Comment by mistyn8** [comment]
constrain and info are from the default embed core prop editor nothing that is custom specifically that we've added.. but in terms of value add.. an examine search on embed_url contains youtube for instance? or using examine.result to list embeds and urls (without having to get the assoc IPublisedContent.)

I guess it's just for convenience, as can parse this json in a examine gathering node approach.

**Comment by dawoe** [comment]
@mistyn8 are you sure you are using my property editor, because I am not storing constrain and info.

**Comment by dawoe** [comment]
@mistyn8 I am closing this one because I don't think this is issue is related to my package
