### ISSUE TITLE
Support for Umbraco 13

### ISSUE THREAD

**Issue by bjarnef** [dawoe/OEmbed-Picker-Property-Editor#33]
Umbraco 13 has just been released https://umbraco.com/blog/umbraco-13-lts-release/ 🥳🎉

So hopefully this package we get an updated version (version 13 I guess to align to version number?) 🤞
https://www.nuget.org/packages/Dawoe.OEmbedPickerPropertyEditor

**Comment by arknu** [comment]
I made a PR to support Umbraco 13 here: https://github.com/dawoe/OEmbed-Picker-Property-Editor/pull/34

**Comment by D-Inventor** [comment]
I would love to see this because we rely quite heavily on this package. It's the only package that keeps us from updating to Umbraco 13 at the moment.

**Comment by dawoe** [comment]
@bjarnef @D-Inventor @arknu 

The V13 release will be on nuget soon.

Dave
