### ISSUE TITLE
Constraint toggle cannot be turned off

### ISSUE THREAD

**Issue by robjakedorsett** [dawoe/OEmbed-Picker-Property-Editor#35]
Browser: windows Chrome v.124
Umbraco version 13.2.0

Steps to reproduce:

1. Open any page with Embed Picker component
2. Edit that Embed Picker component
3. Turn Constraint toggle off
4. Submit
5. Open Edit again

Expected result:

Constraint can be applied and the toggle can be turned off

Actual result:

Constraint toggle is not turning off

![image](https://github.com/dawoe/OEmbed-Picker-Property-Editor/assets/47298040/5dc93092-4627-40de-aa7e-90f53733ce58)

**Comment by dawoe** [comment]
Hi @robjakedorsett 

The embed dialog (which has the constraint toggle) is part of the Umbraco CMS and does not belong to this package.

I think you should create a ticket on the Umbraco CMS issue tracker
