### ISSUE TITLE
Can't Create Data Type Through Code

### ISSUE THREAD

**Issue by 0Neji** [dawoe/OEmbed-Picker-Property-Editor#4]
I'm working on a project which needs to initialise various data types through code. I've been able to successfully do this with a handful of the core Umbraco property editors. For example, to create a Nested Content Data Type:

    IDataEditor dataEditor = new NestedContentPropertyEditor(Logger, new System.Lazy<PropertyEditorCollection>());
                
    dataType = new DataType(dataEditor, 1);

I'm attempting to do the same with this package but the classes are locked down using `internal`. As per the Umbraco editors, I'd expect to be able to create this the same way - would it be possible to change the classes to allow data types to be created in other projects?

I'd expect something along these lines to do the job once the changes have been made:

    IDataEditor dataEditor = new OEmbedPickerDataEditor(Logger);

    dataType = new DataType(dataEditor, 1);

    dataType.Configuration = new OEmbedPickerConfiguration()
    {
        AllowMultiple = false
    };

**Comment by dawoe** [comment]
Hi @0Neji 

Would love to see the use case where you need to create them in code.

But for making them public. I will accept a PR for that. I tend to keep most stuff internal when I don't see a need for making them public.

Apperently now there is a need to have them public.

Dave

**Comment by dawoe** [comment]
this is fixed and is already availabel in the latest beta. Will be part of the 4.2.0 release
