### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by ronaldbarendse** [dawoe/OEmbed-Picker-Property-Editor#5]
The current Add-button seems a bit off compared to other pickers:

![Current add button](https://user-images.githubusercontent.com/1051287/65580379-ce7f5900-df79-11e9-9905-4375d1ea26d5.png)

Changing it to be like this would look better:

![New add button](https://user-images.githubusercontent.com/1051287/65580350-c3c4c400-df79-11e9-81d7-f96ee06ea4f4.png)

Also, when only a single item can be selected, the drag-and-drop handle is still shown (maybe to move it over to another property?) and on smaller screens/larger previews, the Remove-button isn't (completely) shown:

![afbeelding](https://user-images.githubusercontent.com/1051287/65580876-c542bc00-df7a-11e9-8bf8-697f92d87fc6.png)

**Comment by ronaldbarendse** [comment]
And there's no background while dragging the item:

![Dragging](https://user-images.githubusercontent.com/1051287/65581742-4f3f5480-df7c-11e9-97c5-b960ff1ff042.png)

**Comment by ronaldbarendse** [comment]
> And there's no background while dragging the item:
> 
> ![Dragging](https://user-images.githubusercontent.com/1051287/65581742-4f3f5480-df7c-11e9-97c5-b960ff1ff042.png)

Looks like this is a problem in Umbraco core, as I also see this when dragging document types in the Nested Content data type editor...

**Comment by dawoe** [comment]
Hi @ronaldbarendse 

Thanks for the feedback. I will keep this open for a next version. I have seen some work being done in core to be able to edit embeds.

But if you are up to it... I accept pull requests 😄

**Comment by TRexStark** [comment]
Hi @dawoe 

I have styled the property in a test project I have and it looks like the below as an example. I can commit the files if you want to merge them.

There is a new stylesheet added and the view markup changed slightly

<img width="1172" alt="Screen Shot 2020-08-30 at 1 06 35 pm" src="https://user-images.githubusercontent.com/70106895/91650342-b08f7200-eac1-11ea-8090-34c05f45bf10.png">

**Comment by dawoe** [comment]
Hi @TRexStark 

Could you make a PR for this. Looks awesome.

Dave

**Comment by dawoe** [comment]
This is fixed by #7
